### ISSUE TITLE
Week 1 and 2 feedback

### ISSUE THREAD

**Issue by samkap** [xinyu0/tiy-assignments#6]
Cool Design agency looks good. There are a few tiny differences in the font sizes.
The web design template looks a lot like the code from the cool design agency project.
There are a lot of sections and broken images, and elements that you don't need in there. I would simplify it.

With Surf and Paddle it is close to original but it might help to make the popular posts all 25% in width so they all fit next to each other.

**Comment by xinyu0** [comment]
I will fix the font sizes and the popular posts section. Thank you!
